# POST http://localhost:4000/api/users
# content-type: application/json

# {
#     "name": "Nick",
#     "email": "nick@nick.com",
#     "password": "nick@nick"
# }


# POST http://localhost:5000/api/profs
# content-type: application/json

# {
#     "fname": "Zakir",
#     "lname": "Khyzm22",
#     "institution": "Conestoga College"
# }

//GET http://localhost:5000/api/profs


POST http://localhost:5000/api/profs
Content-Type: application/json

{
    "profFName" : "harnish",
    "profLName" : "mistry",
    "profUni" : "Conestoga"
}

